name: anan_onboarding
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14
  cached_network_image:
  shimmer: ^3.0.0
  flash: ^3.0.5+1
  intl:
  after_layout: ^1.2.0
  sizer: ^2.0.15
  streaming_shared_preferences: ^2.0.0
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  provider: ^6.0.5
  injectable: ^2.3.2
  http: ^1.1.0
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  injectable_generator: ^2.4.1
  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/